using System.Collections.Generic;
using System.Net;
using Contracts;
using MbDotNet;
using MbDotNet.Enums;
using MbDotNet.Models.Imposters;

namespace AaServiceImposter
{
    public class AaService : DiscoverableImposter
    {
        public AaService(string serviceName, int port, bool serviceRecordRequests, IClient client, ICollection<Imposter> imposters)
            : base(port, MbDotNet.Enums.Protocol.Http, serviceName, serviceRecordRequests, client, imposters) { }

        public override void SetUpStubbs()
        {
            Imposter.AddStub()
                .OnPathAndMethodEqual("/Provisioning.asmx", Method.Post)
                .ReturnsBody(HttpStatusCode.OK, "<? xml version = \"1.0\" encoding = \"utf-8\" ?><soap: Envelope xmlns: xsi = \"http://www.w3.org/2001/XMLSchema-instance\" xmlns: xsd = \"http://www.w3.org/2001/XMLSchema\" xmlns: soap = \"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetLicencesForCompanyResponse xmlns = \"http://www.fleetriskmanager.com/ns/LicenceCheck/\"><GetLicencesForCompanyResult><SimpleLicence><Active>boolean</Active><Current>boolean</Current><ID>int</ID><Number>string</Number><ExpiryDate>dateTime</ExpiryDate><DriversLicenceChecks><SimpleLicenceCheck xsi: nil=\"true\" /><SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string </ NomineeLastName >< NomineeDateOfBirth > dateTime </ NomineeDateOfBirth >< LatestMandateSignedDate > dateTime </ LatestMandateSignedDate >< EstimatedNextCheckDate > dateTime </ EstimatedNextCheckDate ></ SimpleLicence >< SimpleLicence >< Active > boolean </ Active >< Current > boolean </ Current >< ID > int </ ID >< Number > string </ Number >< ExpiryDate > dateTime </ ExpiryDate >< DriversLicenceChecks >< SimpleLicenceCheck xsi: nil = \"true\" />< SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string</ NomineeLastName><NomineeDateOfBirth>dateTime</ NomineeDateOfBirth><LatestMandateSignedDate> dateTime </ LatestMandateSignedDate><EstimatedNextCheckDate> dateTime </ EstimatedNextCheckDate></ SimpleLicence></ GetLicencesForCompanyResult></ GetLicencesForCompanyResponse></ soap:Body></ soap:Envelope>");
               
            Imposter.AddStub()
                .OnPathAndMethodEqual("/LicenceCheckWebservice.asmx", Method.Post)
                .ReturnsBody(HttpStatusCode.OK, "<? xml version = \"1.0\" encoding = \"utf-8\" ?><soap: Envelope xmlns: xsi = \"http://www.w3.org/2001/XMLSchema-instance\" xmlns: xsd = \"http://www.w3.org/2001/XMLSchema\" xmlns: soap = \"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetLicencesForCompanyResponse xmlns = \"http://www.fleetriskmanager.com/ns/LicenceCheck/\"><GetLicencesForCompanyResult><SimpleLicence><Active>boolean</Active><Current>boolean</Current><ID>int</ID><Number>string</Number><ExpiryDate>dateTime</ExpiryDate><DriversLicenceChecks><SimpleLicenceCheck xsi: nil=\"true\" /><SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string </ NomineeLastName >< NomineeDateOfBirth > dateTime </ NomineeDateOfBirth >< LatestMandateSignedDate > dateTime </ LatestMandateSignedDate >< EstimatedNextCheckDate > dateTime </ EstimatedNextCheckDate ></ SimpleLicence >< SimpleLicence >< Active > boolean </ Active >< Current > boolean </ Current >< ID > int </ ID >< Number > string </ Number >< ExpiryDate > dateTime </ ExpiryDate >< DriversLicenceChecks >< SimpleLicenceCheck xsi: nil = \"true\" />< SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string</ NomineeLastName><NomineeDateOfBirth>dateTime</ NomineeDateOfBirth><LatestMandateSignedDate> dateTime </ LatestMandateSignedDate><EstimatedNextCheckDate> dateTime </ EstimatedNextCheckDate></ SimpleLicence></ GetLicencesForCompanyResult></ GetLicencesForCompanyResponse></ soap:Body></ soap:Envelope>");
            
            Imposter.AddStub()
                .OnPathAndMethodEqual("/AssessmentService.asmx", Method.Post)
                .ReturnsBody(HttpStatusCode.OK, "<? xml version = \"1.0\" encoding = \"utf-8\" ?><soap: Envelope xmlns: xsi = \"http://www.w3.org/2001/XMLSchema-instance\" xmlns: xsd = \"http://www.w3.org/2001/XMLSchema\" xmlns: soap = \"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetLicencesForCompanyResponse xmlns = \"http://www.fleetriskmanager.com/ns/LicenceCheck/\"><GetLicencesForCompanyResult><SimpleLicence><Active>boolean</Active><Current>boolean</Current><ID>int</ID><Number>string</Number><ExpiryDate>dateTime</ExpiryDate><DriversLicenceChecks><SimpleLicenceCheck xsi: nil=\"true\" /><SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string </ NomineeLastName >< NomineeDateOfBirth > dateTime </ NomineeDateOfBirth >< LatestMandateSignedDate > dateTime </ LatestMandateSignedDate >< EstimatedNextCheckDate > dateTime </ EstimatedNextCheckDate ></ SimpleLicence >< SimpleLicence >< Active > boolean </ Active >< Current > boolean </ Current >< ID > int </ ID >< Number > string </ Number >< ExpiryDate > dateTime </ ExpiryDate >< DriversLicenceChecks >< SimpleLicenceCheck xsi: nil = \"true\" />< SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string</ NomineeLastName><NomineeDateOfBirth>dateTime</ NomineeDateOfBirth><LatestMandateSignedDate> dateTime </ LatestMandateSignedDate><EstimatedNextCheckDate> dateTime </ EstimatedNextCheckDate></ SimpleLicence></ GetLicencesForCompanyResult></ GetLicencesForCompanyResponse></ soap:Body></ soap:Envelope>");
            
            Imposter.AddStub()
                .OnPathAndMethodEqual("/OnlineLearningService.asmx", Method.Post)
                .ReturnsBody(HttpStatusCode.OK, "<? xml version = \"1.0\" encoding = \"utf-8\" ?><soap: Envelope xmlns: xsi = \"http://www.w3.org/2001/XMLSchema-instance\" xmlns: xsd = \"http://www.w3.org/2001/XMLSchema\" xmlns: soap = \"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetLicencesForCompanyResponse xmlns = \"http://www.fleetriskmanager.com/ns/LicenceCheck/\"><GetLicencesForCompanyResult><SimpleLicence><Active>boolean</Active><Current>boolean</Current><ID>int</ID><Number>string</Number><ExpiryDate>dateTime</ExpiryDate><DriversLicenceChecks><SimpleLicenceCheck xsi: nil=\"true\" /><SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string </ NomineeLastName >< NomineeDateOfBirth > dateTime </ NomineeDateOfBirth >< LatestMandateSignedDate > dateTime </ LatestMandateSignedDate >< EstimatedNextCheckDate > dateTime </ EstimatedNextCheckDate ></ SimpleLicence >< SimpleLicence >< Active > boolean </ Active >< Current > boolean </ Current >< ID > int </ ID >< Number > string </ Number >< ExpiryDate > dateTime </ ExpiryDate >< DriversLicenceChecks >< SimpleLicenceCheck xsi: nil = \"true\" />< SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string</ NomineeLastName><NomineeDateOfBirth>dateTime</ NomineeDateOfBirth><LatestMandateSignedDate> dateTime </ LatestMandateSignedDate><EstimatedNextCheckDate> dateTime </ EstimatedNextCheckDate></ SimpleLicence></ GetLicencesForCompanyResult></ GetLicencesForCompanyResponse></ soap:Body></ soap:Envelope>");
            
            Imposter.AddStub()
                .OnPathAndMethodEqual("/TaskAllocation.asmx", Method.Post)
                .ReturnsBody(HttpStatusCode.OK, "<? xml version = \"1.0\" encoding = \"utf-8\" ?><soap: Envelope xmlns: xsi = \"http://www.w3.org/2001/XMLSchema-instance\" xmlns: xsd = \"http://www.w3.org/2001/XMLSchema\" xmlns: soap = \"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetLicencesForCompanyResponse xmlns = \"http://www.fleetriskmanager.com/ns/LicenceCheck/\"><GetLicencesForCompanyResult><SimpleLicence><Active>boolean</Active><Current>boolean</Current><ID>int</ID><Number>string</Number><ExpiryDate>dateTime</ExpiryDate><DriversLicenceChecks><SimpleLicenceCheck xsi: nil=\"true\" /><SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string </ NomineeLastName >< NomineeDateOfBirth > dateTime </ NomineeDateOfBirth >< LatestMandateSignedDate > dateTime </ LatestMandateSignedDate >< EstimatedNextCheckDate > dateTime </ EstimatedNextCheckDate ></ SimpleLicence >< SimpleLicence >< Active > boolean </ Active >< Current > boolean </ Current >< ID > int </ ID >< Number > string </ Number >< ExpiryDate > dateTime </ ExpiryDate >< DriversLicenceChecks >< SimpleLicenceCheck xsi: nil = \"true\" />< SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string</ NomineeLastName><NomineeDateOfBirth>dateTime</ NomineeDateOfBirth><LatestMandateSignedDate> dateTime </ LatestMandateSignedDate><EstimatedNextCheckDate> dateTime </ EstimatedNextCheckDate></ SimpleLicence></ GetLicencesForCompanyResult></ GetLicencesForCompanyResponse></ soap:Body></ soap:Envelope>");
            
            Imposter.AddStub()
                .OnPathAndMethodEqual("/CourseDataWebservice.asmx", Method.Post)
                .ReturnsBody(HttpStatusCode.OK, "<? xml version = \"1.0\" encoding = \"utf-8\" ?><soap: Envelope xmlns: xsi = \"http://www.w3.org/2001/XMLSchema-instance\" xmlns: xsd = \"http://www.w3.org/2001/XMLSchema\" xmlns: soap = \"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><GetLicencesForCompanyResponse xmlns = \"http://www.fleetriskmanager.com/ns/LicenceCheck/\"><GetLicencesForCompanyResult><SimpleLicence><Active>boolean</Active><Current>boolean</Current><ID>int</ID><Number>string</Number><ExpiryDate>dateTime</ExpiryDate><DriversLicenceChecks><SimpleLicenceCheck xsi: nil=\"true\" /><SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string </ NomineeLastName >< NomineeDateOfBirth > dateTime </ NomineeDateOfBirth >< LatestMandateSignedDate > dateTime </ LatestMandateSignedDate >< EstimatedNextCheckDate > dateTime </ EstimatedNextCheckDate ></ SimpleLicence >< SimpleLicence >< Active > boolean </ Active >< Current > boolean </ Current >< ID > int </ ID >< Number > string </ Number >< ExpiryDate > dateTime </ ExpiryDate >< DriversLicenceChecks >< SimpleLicenceCheck xsi: nil = \"true\" />< SimpleLicenceCheck xsi: nil = \"true\" /></ DriversLicenceChecks >< Points > int </ Points >< NomineeEmailAddress > string </ NomineeEmailAddress >< UserId > int </ UserId >< NomineeFirstNames > string </ NomineeFirstNames >< NomineeLastName > string</ NomineeLastName><NomineeDateOfBirth>dateTime</ NomineeDateOfBirth><LatestMandateSignedDate> dateTime </ LatestMandateSignedDate><EstimatedNextCheckDate> dateTime </ EstimatedNextCheckDate></ SimpleLicence></ GetLicencesForCompanyResult></ GetLicencesForCompanyResponse></ soap:Body></ soap:Envelope>");
        }
    }
}